CREATE TABLE [CUSTOMERS ORDERS]
(
[ORDER ID] INT,
[CUSTOMER ID] INT,
[PRODUCT ID] INT,
[ORDER DATE] DATETIME,
[TOTAL AMOUNT] FLOAT
)

INSERT INTO [CUSTOMERS ORDERS] VALUES
(1, 101, 1, 2022-02-01, 100.00),
(2, 102, 2, 2022-03-01, 200.00),
(3, 103, 1, 2022-04-01, 50.00),
(4, 101, 3, 2022-05-01, 150.00),
(5, 102, 1, 2022-06-01, 75.00),
(6, 104, 2, 2022-06-01, 300.00),
(7, 103, 1, 2022-07-01, 25.00),
(8, 101, 2, 2022-08-01, 50.00)


CREATE TABLE [CUSTOMERS]
(
[CUSTOMER ID] NUMERIC,
[CUSTOMER NAME] VARCHAR(50),
[COUNTRY] VARCHAR(50)
)

INSERT INTO [CUSTOMERS] VALUES
(101, 'JOHN SMITH', 'USA'),
(102, 'MARIA GARCIA', 'SPAIN'),
(103, 'SATO TAKAHASHI', 'JAPAN'),
(104, 'HANS MILLER', 'GERMANY')

CREATE TABLE [PRODUCTS]
(
[PRODUCT ID] NUMERIC,
[PRODUCT NAME] VARCHAR(50),
[PRICE] NUMERIC
)

INSERT INTO [PRODUCTS] VALUES
(1, 'PRODUCT A', 50.00),
(2, 'PRODUCT B', 100.00),
(3, 'PRODUCT C', 75.00)


SELECT * FROM [dbo].[CUSTOMERS]

SELECT * FROM [dbo].[CUSTOMERS ORDERS]

SELECT * FROM [dbo].[PRODUCTS]

CREATE TABLE #CUSTOMER
(
[CUSTOMER ID] NUMERIC,
[CUSTOMER NAME] VARCHAR (50),
COUNTRY VARCHAR (50),
[ORDER ID] NUMERIC,
[PRODUCT ID] NUMERIC,
[ORDER DATE] DATETIME,
[TOTAL AMOUNT] NUMERIC,
[PRODUCT NAME] VARCHAR (50),
PRICE NUMERIC
)
INSERT INTO #CUSTOMER
SELECT CID.[CUSTOMER ID], [CUSTOMER NAME], COUNTRY, [ORDER ID], PRDTS.[PRODUCT ID],[ORDER DATE],[TOTAL AMOUNT],[PRODUCT NAME],PRICE
FROM [dbo].[CUSTOMERS] AS CID
FULL OUTER JOIN [dbo].[CUSTOMERS ORDERS] AS CO
  ON CID.[CUSTOMER ID] = CO.[CUSTOMER ID]
FULL OUTER JOIN [dbo].[PRODUCTS] AS PRDTS
  ON CO.[PRODUCT ID] = PRDTS.[PRODUCT ID]
ORDER BY [ORDER ID]
SELECT * FROM #CUSTOMER

SELECT [CUSTOMER NAME], COUNTRY, SUM(PRICE) AS [TOTAL REVENUE GENERATED], count([PRODUCT ID]) AS [TOTAL NUMBER OF PRODUCTS PER CUSTOMER], AVG(PRICE) AS [AVG PRICE OF PRODUCT PER CUSTOMER]
FROM #CUSTOMER
GROUP BY [CUSTOMER NAME], COUNTRY
ORDER BY [TOTAL REVENUE GENERATED] DESC




